server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  datasource:
    url: jdbc:mysql://${db_endpoint}/${db_dbname}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

logging:
  level:
    ckell: info
